require('dotenv').config();
const mongoose = require('mongoose');
const Food = require('../src/models/Food');

const foods = [
  // BREAKFAST
  { name: 'Idli', nameLocal: 'இட்லி', category: 'breakfast', cuisine: 'south_indian', servingSize: 100, commonServings: [{ label: '1 piece (40g)', grams: 40 }, { label: '2 pieces', grams: 80 }], nutrients: { calories: 58, protein: 2.0, carbs: 11.5, netCarbs: 11.0, sugar: 0.3, fiber: 0.5, fat: 0.4, saturatedFat: 0.1, vitaminB1: 0.02, vitaminB3: 0.3, calcium: 14, iron: 0.4, magnesium: 15, phosphorus: 40, potassium: 95, sodium: 180 } },
  { name: 'Mini Idli', nameLocal: 'குழி பணியாரம்', category: 'breakfast', cuisine: 'south_indian', servingSize: 100, commonServings: [{ label: '5 pieces (100g)', grams: 100 }], nutrients: { calories: 60, protein: 2.1, carbs: 11.8, netCarbs: 11.3, sugar: 0.3, fiber: 0.5, fat: 0.5, saturatedFat: 0.1, calcium: 14, iron: 0.4, sodium: 185 } },
  { name: 'Rava Idli', nameLocal: 'ரவா இட்லி', category: 'breakfast', cuisine: 'south_indian', servingSize: 100, commonServings: [{ label: '1 piece (60g)', grams: 60 }], nutrients: { calories: 120, protein: 3.5, carbs: 20, netCarbs: 19.5, sugar: 1, fiber: 0.5, fat: 3.5, saturatedFat: 1.5, calcium: 20, iron: 0.8, sodium: 300 } },
  { name: 'Plain Dosa', nameLocal: 'தோசை', category: 'breakfast', cuisine: 'south_indian', servingSize: 100, commonServings: [{ label: '1 medium (80g)', grams: 80 }, { label: '1 large (120g)', grams: 120 }], nutrients: { calories: 168, protein: 3.8, carbs: 26, netCarbs: 25.7, sugar: 0.5, fiber: 0.3, fat: 5.5, saturatedFat: 1.2, calcium: 12, iron: 0.5, sodium: 190 } },
  { name: 'Masala Dosa', nameLocal: 'மசாலா தோசை', category: 'breakfast', cuisine: 'south_indian', servingSize: 100, commonServings: [{ label: '1 piece (200g)', grams: 200 }], nutrients: { calories: 175, protein: 4.0, carbs: 26, netCarbs: 25.5, sugar: 1.5, fiber: 0.5, fat: 6.5, saturatedFat: 1.5, calcium: 20, iron: 0.8, potassium: 180, sodium: 250 } },
  { name: 'Ghee Roast Dosa', nameLocal: 'நெய் ரோஸ்ட் தோசை', category: 'breakfast', cuisine: 'south_indian', servingSize: 100, commonServings: [{ label: '1 piece (120g)', grams: 120 }], nutrients: { calories: 225, protein: 4.0, carbs: 25, netCarbs: 24.7, sugar: 0.3, fiber: 0.3, fat: 12, saturatedFat: 7, cholesterol: 25, sodium: 220 } },
  { name: 'Onion Dosa', nameLocal: 'வெங்காய தோசை', category: 'breakfast', cuisine: 'south_indian', servingSize: 100, commonServings: [{ label: '1 piece (100g)', grams: 100 }], nutrients: { calories: 170, protein: 3.9, carbs: 25, netCarbs: 24.5, sugar: 1.5, fiber: 0.5, fat: 6, saturatedFat: 1.3, calcium: 18, iron: 0.6, sodium: 200 } },
  { name: 'Podi Dosa', nameLocal: 'பொடி தோசை', category: 'breakfast', cuisine: 'south_indian', servingSize: 100, commonServings: [{ label: '1 piece (120g)', grams: 120 }], nutrients: { calories: 195, protein: 5, carbs: 25, netCarbs: 24, sugar: 0.4, fiber: 1, fat: 8, saturatedFat: 2, iron: 1, sodium: 280 } },
  { name: 'Uttapam', nameLocal: 'உத்தப்பம்', category: 'breakfast', cuisine: 'south_indian', servingSize: 100, commonServings: [{ label: '1 piece (150g)', grams: 150 }], nutrients: { calories: 120, protein: 4.0, carbs: 20, netCarbs: 19, sugar: 2, fiber: 1, fat: 3, saturatedFat: 0.5, calcium: 25, iron: 0.8, sodium: 230 } },
  { name: 'Ven Pongal', nameLocal: 'வெண் பொங்கல்', category: 'breakfast', cuisine: 'south_indian', servingSize: 100, commonServings: [{ label: '1 cup (200g)', grams: 200 }], nutrients: { calories: 92, protein: 3.5, carbs: 15, netCarbs: 14, sugar: 0.5, fiber: 1, fat: 2.5, saturatedFat: 1, calcium: 18, iron: 0.7, magnesium: 20, sodium: 200 } },
  { name: 'Rava Upma', nameLocal: 'ரவா உப்மா', category: 'breakfast', cuisine: 'south_indian', servingSize: 100, commonServings: [{ label: '1 cup (200g)', grams: 200 }], nutrients: { calories: 96, protein: 2.8, carbs: 16, netCarbs: 15.5, sugar: 1, fiber: 0.5, fat: 3, saturatedFat: 0.8, calcium: 10, iron: 0.5, sodium: 280 } },
  { name: 'Semiya Upma', nameLocal: 'சேமியா உப்மா', category: 'breakfast', cuisine: 'south_indian', servingSize: 100, commonServings: [{ label: '1 cup (180g)', grams: 180 }], nutrients: { calories: 100, protein: 3, carbs: 18, netCarbs: 17, sugar: 1, fiber: 1, fat: 2.5, saturatedFat: 0.5, calcium: 12, iron: 0.6, sodium: 250 } },
  { name: 'Appam', nameLocal: 'ஆப்பம்', category: 'breakfast', cuisine: 'south_indian', servingSize: 100, commonServings: [{ label: '1 piece (60g)', grams: 60 }], nutrients: { calories: 110, protein: 2.5, carbs: 22, netCarbs: 21.5, sugar: 0.5, fiber: 0.5, fat: 1.5, saturatedFat: 0.8, calcium: 10, iron: 0.4, sodium: 150 } },
  { name: 'Idiyappam', nameLocal: 'இடியாப்பம்', category: 'breakfast', cuisine: 'south_indian', servingSize: 100, commonServings: [{ label: '2 pieces (100g)', grams: 100 }], nutrients: { calories: 145, protein: 2, carbs: 30, netCarbs: 29.5, sugar: 0, fiber: 0.5, fat: 2, saturatedFat: 1, calcium: 8, iron: 0.3, sodium: 100 } },
  { name: 'Poori', nameLocal: 'பூரி', category: 'breakfast', cuisine: 'south_indian', servingSize: 100, commonServings: [{ label: '1 piece (40g)', grams: 40 }], nutrients: { calories: 337, protein: 7, carbs: 47, netCarbs: 44, sugar: 0, fiber: 3, fat: 14, saturatedFat: 2, iron: 2, sodium: 380 } },
  { name: 'Chapati', nameLocal: 'சப்பாத்தி', category: 'breakfast', cuisine: 'indian', servingSize: 100, commonServings: [{ label: '1 piece (45g)', grams: 45 }], nutrients: { calories: 240, protein: 7.5, carbs: 44, netCarbs: 41, sugar: 0.5, fiber: 3, fat: 4, saturatedFat: 0.5, iron: 2, magnesium: 25, sodium: 220 } },
  { name: 'Parotta', nameLocal: 'பரோட்டா', category: 'breakfast', cuisine: 'south_indian', servingSize: 100, commonServings: [{ label: '1 piece (80g)', grams: 80 }], nutrients: { calories: 320, protein: 6, carbs: 42, netCarbs: 40, sugar: 1, fiber: 2, fat: 14, saturatedFat: 4, cholesterol: 10, sodium: 400 } },

  // RICE & LUNCH
  { name: 'White Rice', nameLocal: 'வெள்ளை சாதம்', category: 'lunch', cuisine: 'south_indian', servingSize: 100, commonServings: [{ label: '1 cup cooked (175g)', grams: 175 }, { label: 'Small plate (250g)', grams: 250 }], nutrients: { calories: 130, protein: 2.7, carbs: 28, netCarbs: 27.8, sugar: 0.1, fiber: 0.2, fat: 0.3, saturatedFat: 0.1, iron: 0.2, magnesium: 13, phosphorus: 43, potassium: 35, sodium: 1 } },
  { name: 'Brown Rice', nameLocal: 'கைகுத்தல் அரிசி', category: 'lunch', cuisine: 'indian', servingSize: 100, commonServings: [{ label: '1 cup cooked (195g)', grams: 195 }], nutrients: { calories: 123, protein: 2.7, carbs: 25.5, netCarbs: 24.5, sugar: 0.4, fiber: 1.0, fat: 1.0, saturatedFat: 0.2, vitaminB1: 0.1, vitaminB3: 1.5, iron: 0.5, magnesium: 43, phosphorus: 83, potassium: 79, sodium: 5 } },
  { name: 'Sambar Rice', nameLocal: 'சாம்பார் சாதம்', category: 'lunch', cuisine: 'south_indian', servingSize: 100, commonServings: [{ label: '1 plate (300g)', grams: 300 }], nutrients: { calories: 105, protein: 3.5, carbs: 20, netCarbs: 18, sugar: 1, fiber: 2, fat: 1.5, saturatedFat: 0.3, iron: 1, potassium: 200, sodium: 350 } },
  { name: 'Curd Rice', nameLocal: 'தயிர் சாதம்', category: 'lunch', cuisine: 'south_indian', servingSize: 100, commonServings: [{ label: '1 cup (200g)', grams: 200 }], nutrients: { calories: 110, protein: 3.5, carbs: 18, netCarbs: 17.5, sugar: 2.5, fiber: 0.5, fat: 2.5, saturatedFat: 1.5, calcium: 80, phosphorus: 70, sodium: 200 } },
  { name: 'Tomato Rice', nameLocal: 'தக்காளி சாதம்', category: 'lunch', cuisine: 'south_indian', servingSize: 100, commonServings: [{ label: '1 cup (200g)', grams: 200 }], nutrients: { calories: 145, protein: 2.8, carbs: 22, netCarbs: 21, sugar: 2, fiber: 1, fat: 5.5, saturatedFat: 1, vitaminC: 10, iron: 0.6, sodium: 280 } },
  { name: 'Lemon Rice', nameLocal: 'எலுமிச்சை சாதம்', category: 'lunch', cuisine: 'south_indian', servingSize: 100, commonServings: [{ label: '1 cup (200g)', grams: 200 }], nutrients: { calories: 150, protein: 2.5, carbs: 23, netCarbs: 22, sugar: 0.5, fiber: 1, fat: 5.5, saturatedFat: 0.5, vitaminC: 8, iron: 0.8, sodium: 260 } },
  { name: 'Coconut Rice', nameLocal: 'தேங்காய் சாதம்', category: 'lunch', cuisine: 'south_indian', servingSize: 100, commonServings: [{ label: '1 cup (200g)', grams: 200 }], nutrients: { calories: 175, protein: 2.5, carbs: 22, netCarbs: 20, sugar: 1, fiber: 2, fat: 8, saturatedFat: 6, iron: 0.5, potassium: 120, sodium: 180 } },
  { name: 'Tamarind Rice', nameLocal: 'புளியோதரை', category: 'lunch', cuisine: 'south_indian', servingSize: 100, commonServings: [{ label: '1 cup (200g)', grams: 200 }], nutrients: { calories: 155, protein: 2.5, carbs: 24, netCarbs: 22.5, sugar: 2.5, fiber: 1.5, fat: 5.5, saturatedFat: 0.8, iron: 1.2, potassium: 140, sodium: 320 } },
  { name: 'Jeera Rice', nameLocal: 'சீரக சாதம்', category: 'lunch', cuisine: 'indian', servingSize: 100, commonServings: [{ label: '1 cup (180g)', grams: 180 }], nutrients: { calories: 148, protein: 2.8, carbs: 24, netCarbs: 23.5, sugar: 0.2, fiber: 0.5, fat: 4.5, saturatedFat: 2, iron: 0.5, sodium: 180 } },

  // CURRIES
  { name: 'Sambar', nameLocal: 'சாம்பார்', category: 'lunch', cuisine: 'south_indian', servingSize: 100, commonServings: [{ label: '1 ladle (100ml)', grams: 100 }, { label: '2 ladles (200ml)', grams: 200 }], nutrients: { calories: 45, protein: 2.5, carbs: 6, netCarbs: 4.5, sugar: 2, fiber: 1.5, fat: 1.5, saturatedFat: 0.3, vitaminA: 120, vitaminC: 12, iron: 1.2, potassium: 220, sodium: 380 } },
  { name: 'Rasam', nameLocal: 'ரசம்', category: 'lunch', cuisine: 'south_indian', servingSize: 100, commonServings: [{ label: '1 cup (200ml)', grams: 200 }], nutrients: { calories: 25, protein: 1, carbs: 4, netCarbs: 3.5, sugar: 1, fiber: 0.5, fat: 1, saturatedFat: 0.2, vitaminC: 5, iron: 0.5, potassium: 120, sodium: 250 } },
  { name: 'Kootu', nameLocal: 'கூட்டு', category: 'lunch', cuisine: 'south_indian', servingSize: 100, commonServings: [{ label: '1 serving (120g)', grams: 120 }], nutrients: { calories: 90, protein: 4, carbs: 10, netCarbs: 7, sugar: 2, fiber: 3, fat: 4, saturatedFat: 2, calcium: 40, iron: 1.5, potassium: 280, sodium: 200 } },
  { name: 'Poriyal', nameLocal: 'பொரியல்', category: 'lunch', cuisine: 'south_indian', servingSize: 100, commonServings: [{ label: '1 serving (80g)', grams: 80 }], nutrients: { calories: 75, protein: 2, carbs: 8, netCarbs: 6, sugar: 2, fiber: 2, fat: 4, saturatedFat: 2, vitaminC: 15, iron: 0.8, potassium: 250, sodium: 180 } },
  { name: 'Avial', nameLocal: 'அவியல்', category: 'lunch', cuisine: 'south_indian', servingSize: 100, commonServings: [{ label: '1 serving (150g)', grams: 150 }], nutrients: { calories: 80, protein: 2.5, carbs: 8, netCarbs: 6, sugar: 2, fiber: 2, fat: 4.5, saturatedFat: 3, vitaminA: 200, vitaminC: 20, calcium: 30, potassium: 300, sodium: 150 } },
  { name: 'Kurma', nameLocal: 'குர்மா', category: 'lunch', cuisine: 'south_indian', servingSize: 100, commonServings: [{ label: '1 serving (150g)', grams: 150 }], nutrients: { calories: 115, protein: 3.5, carbs: 10, netCarbs: 8, sugar: 3, fiber: 2, fat: 7, saturatedFat: 3, calcium: 45, iron: 1, potassium: 250, sodium: 320 } },
  { name: 'Chicken Curry', nameLocal: 'கோழி கறி', category: 'lunch', cuisine: 'south_indian', servingSize: 100, commonServings: [{ label: '1 serving (150g)', grams: 150 }], nutrients: { calories: 165, protein: 14, carbs: 5, netCarbs: 4, sugar: 1.5, fiber: 1, fat: 10, saturatedFat: 2.5, cholesterol: 65, iron: 1.2, potassium: 280, sodium: 400 } },
  { name: 'Fish Curry', nameLocal: 'மீன் குழம்பு', category: 'lunch', cuisine: 'south_indian', servingSize: 100, commonServings: [{ label: '1 serving (150g)', grams: 150 }], nutrients: { calories: 135, protein: 14, carbs: 4, netCarbs: 3, sugar: 1, fiber: 1, fat: 7, saturatedFat: 1.5, cholesterol: 60, omega3: 0.8, vitaminD: 4, calcium: 40, iron: 1, potassium: 320, sodium: 450 } },
  { name: 'Mutton Curry', nameLocal: 'ஆட்டு கறி', category: 'lunch', cuisine: 'south_indian', servingSize: 100, commonServings: [{ label: '1 serving (150g)', grams: 150 }], nutrients: { calories: 200, protein: 16, carbs: 4, netCarbs: 3, sugar: 1, fiber: 1, fat: 13, saturatedFat: 4.5, cholesterol: 80, iron: 2.5, zinc: 4, potassium: 310, sodium: 420 } },

  // PROTEIN SOURCES
  { name: 'Chicken Breast', nameLocal: 'சிக்கன் ப்ரெஸ்ட்', category: 'protein', cuisine: 'global', servingSize: 100, commonServings: [{ label: '1 piece (120g)', grams: 120 }, { label: '1 piece (150g)', grams: 150 }], nutrients: { calories: 165, protein: 31, completeProtein: 31, carbs: 0, netCarbs: 0, sugar: 0, fiber: 0, fat: 3.6, saturatedFat: 1, monounsaturatedFat: 1.2, cholesterol: 85, vitaminB3: 14, vitaminB6: 0.9, vitaminB12: 0.3, iron: 0.7, phosphorus: 220, potassium: 256, sodium: 74, zinc: 0.9, selenium: 27 } },
  { name: 'Chicken Thigh', nameLocal: 'சிக்கன் தொடை', category: 'protein', cuisine: 'global', servingSize: 100, commonServings: [{ label: '1 piece (100g)', grams: 100 }], nutrients: { calories: 209, protein: 26, completeProtein: 26, carbs: 0, netCarbs: 0, sugar: 0, fiber: 0, fat: 11, saturatedFat: 3, cholesterol: 90, vitaminB3: 8, vitaminB6: 0.5, iron: 1, potassium: 238, sodium: 88, zinc: 2.4 } },
  { name: 'Egg Whole', nameLocal: 'முட்டை', category: 'protein', cuisine: 'global', servingSize: 100, commonServings: [{ label: '1 large egg (50g)', grams: 50 }, { label: '2 eggs (100g)', grams: 100 }], nutrients: { calories: 143, protein: 13, completeProtein: 13, carbs: 0.7, netCarbs: 0.7, sugar: 0.4, fiber: 0, fat: 9.5, saturatedFat: 3, monounsaturatedFat: 3.5, cholesterol: 372, vitaminA: 160, vitaminB2: 0.5, vitaminB12: 1.1, vitaminD: 2, vitaminK: 0.3, calcium: 56, iron: 1.8, phosphorus: 198, potassium: 138, sodium: 142, zinc: 1.3, selenium: 30 } },
  { name: 'Egg White', nameLocal: 'முட்டை வெள்ளை', category: 'protein', cuisine: 'global', servingSize: 100, commonServings: [{ label: '1 white (33g)', grams: 33 }, { label: '3 whites (100g)', grams: 100 }], nutrients: { calories: 52, protein: 11, completeProtein: 11, carbs: 0.7, netCarbs: 0.7, sugar: 0.5, fiber: 0, fat: 0.2, saturatedFat: 0, cholesterol: 0, vitaminB2: 0.4, vitaminB12: 0.09, sodium: 166, potassium: 163, selenium: 20 } },
  { name: 'Paneer', nameLocal: 'பன்னீர்', category: 'protein', cuisine: 'indian', servingSize: 100, commonServings: [{ label: '50g', grams: 50 }, { label: '100g', grams: 100 }], nutrients: { calories: 265, protein: 18, completeProtein: 18, carbs: 1.2, netCarbs: 1.2, sugar: 0.5, fiber: 0, fat: 20, saturatedFat: 13, cholesterol: 60, calcium: 480, phosphorus: 330, potassium: 104, sodium: 400 } },
  { name: 'Tofu', nameLocal: 'டோஃபு', category: 'protein', cuisine: 'global', servingSize: 100, commonServings: [{ label: '100g', grams: 100 }], nutrients: { calories: 76, protein: 8, completeProtein: 8, carbs: 1.9, netCarbs: 1.5, sugar: 0.6, fiber: 0.4, fat: 4.5, saturatedFat: 0.7, polyunsaturatedFat: 2.5, omega3: 0.3, calcium: 350, iron: 2.5, magnesium: 30, phosphorus: 120, potassium: 150, sodium: 7, zinc: 0.8 } },
  { name: 'Soya Chunks', nameLocal: 'சோயா சங்க்ஸ்', category: 'protein', cuisine: 'indian', servingSize: 100, commonServings: [{ label: 'Raw 30g (yields 90g)', grams: 30 }], tags: ['soy', 'textured vegetable protein'], nutrients: { calories: 345, protein: 52, incompleteProtein: 52, carbs: 33, netCarbs: 28, sugar: 5, fiber: 5, fat: 0.5, saturatedFat: 0.1, polyunsaturatedFat: 0.3, vitaminB1: 0.1, vitaminB2: 0.2, calcium: 200, iron: 9, magnesium: 40, phosphorus: 700, potassium: 2000, sodium: 2, zinc: 5 } },
  { name: 'Green Gram (Moong)', nameLocal: 'பச்சை பயறு', category: 'protein', cuisine: 'indian', servingSize: 100, commonServings: [{ label: '1 cup cooked (200g)', grams: 200 }], nutrients: { calories: 105, protein: 7, incompleteProtein: 7, carbs: 19, netCarbs: 15, sugar: 2, fiber: 4, fat: 0.4, saturatedFat: 0.1, vitaminB1: 0.1, vitaminB9: 160, vitaminC: 1, calcium: 27, iron: 1.4, magnesium: 36, phosphorus: 99, potassium: 266, sodium: 2, zinc: 0.8 } },
  { name: 'Black Channa', nameLocal: 'கருப்பு கொண்டைக்கடலை', category: 'protein', cuisine: 'indian', servingSize: 100, commonServings: [{ label: '1 cup cooked (160g)', grams: 160 }], nutrients: { calories: 164, protein: 8.9, incompleteProtein: 8.9, carbs: 27, netCarbs: 20, sugar: 4.8, fiber: 7, fat: 2.6, saturatedFat: 0.3, vitaminB9: 172, vitaminC: 1.3, calcium: 49, iron: 2.9, magnesium: 48, phosphorus: 168, potassium: 291, sodium: 11, zinc: 1.5 } },
  { name: 'White Channa', nameLocal: 'வெள்ளை கொண்டைக்கடலை', category: 'protein', cuisine: 'indian', servingSize: 100, commonServings: [{ label: '1 cup cooked (160g)', grams: 160 }], nutrients: { calories: 164, protein: 8.9, incompleteProtein: 8.9, carbs: 27, netCarbs: 20, sugar: 4.8, fiber: 7, fat: 2.6, vitaminB9: 172, calcium: 49, iron: 2.9, potassium: 291, sodium: 11, zinc: 1.5 } },
  { name: 'Peanuts', nameLocal: 'வேர்க்கடலை', category: 'protein', cuisine: 'global', servingSize: 100, commonServings: [{ label: 'Handful (30g)', grams: 30 }], nutrients: { calories: 567, protein: 25.8, incompleteProtein: 25.8, carbs: 16, netCarbs: 9.5, sugar: 4, fiber: 6.5, fat: 49.2, saturatedFat: 6.8, monounsaturatedFat: 24.4, polyunsaturatedFat: 15.6, omega6: 15, vitaminB3: 12, vitaminE: 8.3, calcium: 92, iron: 4.6, magnesium: 168, phosphorus: 376, potassium: 705, sodium: 18, zinc: 3.3, selenium: 7 } },
  { name: 'Rajma', nameLocal: 'ராஜ்மா', category: 'protein', cuisine: 'indian', servingSize: 100, commonServings: [{ label: '1 cup cooked (175g)', grams: 175 }], nutrients: { calories: 127, protein: 8.7, incompleteProtein: 8.7, carbs: 22.8, netCarbs: 16.8, sugar: 0.3, fiber: 6, fat: 0.5, vitaminB9: 130, vitaminK: 14.9, calcium: 28, iron: 2.2, magnesium: 45, phosphorus: 144, potassium: 403, sodium: 2, zinc: 1.4 } },
  { name: 'Horse Gram', nameLocal: 'கொள்ளு', category: 'protein', cuisine: 'south_indian', servingSize: 100, commonServings: [{ label: '1 cup cooked (180g)', grams: 180 }], nutrients: { calories: 321, protein: 22, incompleteProtein: 22, carbs: 57, netCarbs: 49, sugar: 5, fiber: 8, fat: 0.5, calcium: 287, iron: 7, phosphorus: 311, potassium: 900 } },
  { name: 'Moong Dal', nameLocal: 'பாசிப்பருப்பு', category: 'protein', cuisine: 'south_indian', servingSize: 100, commonServings: [{ label: '1 cup cooked (200g)', grams: 200 }], nutrients: { calories: 105, protein: 7, incompleteProtein: 7, carbs: 19, netCarbs: 15, sugar: 2, fiber: 4, fat: 0.4, vitaminB9: 159, calcium: 27, iron: 1.4, magnesium: 37, potassium: 270, sodium: 2 } },
  { name: 'Toor Dal', nameLocal: 'துவரம் பருப்பு', category: 'protein', cuisine: 'south_indian', servingSize: 100, commonServings: [{ label: '1 cup cooked (200g)', grams: 200 }], nutrients: { calories: 116, protein: 7, incompleteProtein: 7, carbs: 21, netCarbs: 16, sugar: 2, fiber: 5, fat: 0.4, vitaminB9: 110, calcium: 73, iron: 2.7, magnesium: 62, phosphorus: 178, potassium: 750, sodium: 6 } },
  { name: 'Urad Dal', nameLocal: 'உளுந்தம் பருப்பு', category: 'protein', cuisine: 'south_indian', servingSize: 100, commonServings: [{ label: '1 cup cooked (180g)', grams: 180 }], nutrients: { calories: 341, protein: 25, incompleteProtein: 25, carbs: 59, netCarbs: 50, sugar: 3, fiber: 9, fat: 1.6, calcium: 138, iron: 7.6, magnesium: 134, phosphorus: 379, potassium: 1388 } },
  { name: 'Masoor Dal', nameLocal: 'மசூர் பருப்பு', category: 'protein', cuisine: 'indian', servingSize: 100, commonServings: [{ label: '1 cup cooked (200g)', grams: 200 }], nutrients: { calories: 116, protein: 9, incompleteProtein: 9, carbs: 20, netCarbs: 15, sugar: 1.8, fiber: 7.9, fat: 0.4, vitaminB9: 181, vitaminC: 1.5, iron: 3.3, magnesium: 36, potassium: 369, sodium: 2 } },

  // DAIRY
  { name: 'Milk', nameLocal: 'பால்', category: 'dairy', cuisine: 'global', servingSize: 100, commonServings: [{ label: '1 glass (200ml)', grams: 200 }, { label: '1 cup (240ml)', grams: 240 }], nutrients: { calories: 61, protein: 3.2, completeProtein: 3.2, carbs: 4.8, netCarbs: 4.8, sugar: 4.8, fiber: 0, fat: 3.3, saturatedFat: 2.1, cholesterol: 10, vitaminA: 46, vitaminB2: 0.18, vitaminB12: 0.5, vitaminD: 1.1, calcium: 113, phosphorus: 84, potassium: 150, sodium: 43 } },
  { name: 'Curd', nameLocal: 'தயிர்', category: 'dairy', cuisine: 'indian', servingSize: 100, commonServings: [{ label: '1 cup (200g)', grams: 200 }], nutrients: { calories: 61, protein: 3.5, completeProtein: 3.5, carbs: 4.7, netCarbs: 4.7, sugar: 4.7, fiber: 0, fat: 3.2, saturatedFat: 2.0, cholesterol: 12, vitaminB2: 0.2, vitaminB12: 0.4, calcium: 121, phosphorus: 95, potassium: 141, sodium: 46 } },
  { name: 'Buttermilk', nameLocal: 'மோர்', category: 'drinks', cuisine: 'south_indian', servingSize: 100, commonServings: [{ label: '1 glass (200ml)', grams: 200 }], nutrients: { calories: 40, protein: 3.3, carbs: 4.8, netCarbs: 4.8, sugar: 4.8, fiber: 0, fat: 0.9, saturatedFat: 0.5, vitaminB2: 0.2, vitaminB12: 0.2, calcium: 116, phosphorus: 89, potassium: 151, sodium: 105 } },
  { name: 'Greek Yogurt', nameLocal: 'கிரேக்க தயிர்', category: 'dairy', cuisine: 'global', servingSize: 100, commonServings: [{ label: '1 cup (170g)', grams: 170 }], nutrients: { calories: 59, protein: 10, completeProtein: 10, carbs: 3.6, netCarbs: 3.6, sugar: 3.2, fiber: 0, fat: 0.4, saturatedFat: 0.1, vitaminB12: 0.75, calcium: 111, phosphorus: 132, potassium: 141, sodium: 36 } },

  // FRUITS
  { name: 'Banana', nameLocal: 'வாழைப்பழம்', category: 'fruits', cuisine: 'global', servingSize: 100, commonServings: [{ label: '1 medium (118g)', grams: 118 }, { label: '1 small (80g)', grams: 80 }], nutrients: { calories: 89, protein: 1.1, carbs: 23, netCarbs: 21.5, sugar: 12, fiber: 1.7, fat: 0.3, saturatedFat: 0.1, vitaminB6: 0.4, vitaminC: 8.7, vitaminB9: 20, potassium: 358, magnesium: 27, phosphorus: 22, sodium: 1 } },
  { name: 'Apple', nameLocal: 'ஆப்பிள்', category: 'fruits', cuisine: 'global', servingSize: 100, commonServings: [{ label: '1 medium (182g)', grams: 182 }], nutrients: { calories: 52, protein: 0.3, carbs: 14, netCarbs: 11.7, sugar: 10, fiber: 2.4, fat: 0.2, vitaminC: 4.6, vitaminK: 2.2, potassium: 107, sodium: 1 } },
  { name: 'Orange', nameLocal: 'ஆரஞ்சு', category: 'fruits', cuisine: 'global', servingSize: 100, commonServings: [{ label: '1 medium (131g)', grams: 131 }], nutrients: { calories: 47, protein: 0.9, carbs: 12, netCarbs: 9.6, sugar: 9.3, fiber: 2.4, fat: 0.1, vitaminC: 53.2, vitaminB9: 30, calcium: 40, potassium: 181, sodium: 0 } },
  { name: 'Papaya', nameLocal: 'பப்பாளி', category: 'fruits', cuisine: 'global', servingSize: 100, commonServings: [{ label: '1 cup (145g)', grams: 145 }], nutrients: { calories: 43, protein: 0.5, carbs: 11, netCarbs: 9.2, sugar: 7.8, fiber: 1.8, fat: 0.3, vitaminA: 950, vitaminC: 61, vitaminK: 2.6, vitaminB9: 38, calcium: 20, potassium: 182, sodium: 8 } },
  { name: 'Guava', nameLocal: 'கொய்யா', category: 'fruits', cuisine: 'global', servingSize: 100, commonServings: [{ label: '1 medium (90g)', grams: 90 }], nutrients: { calories: 68, protein: 2.6, carbs: 14, netCarbs: 8.9, sugar: 9.0, fiber: 5.4, fat: 1.0, vitaminC: 228, vitaminA: 624, vitaminB9: 49, calcium: 18, iron: 0.3, potassium: 417, sodium: 2 } },
  { name: 'Watermelon', nameLocal: 'தர்பூசணி', category: 'fruits', cuisine: 'global', servingSize: 100, commonServings: [{ label: '1 slice (300g)', grams: 300 }], nutrients: { calories: 30, protein: 0.6, carbs: 7.6, netCarbs: 7, sugar: 6.2, fiber: 0.4, fat: 0.2, vitaminA: 569, vitaminC: 8.1, potassium: 112, sodium: 1, water: 91 } },
  { name: 'Mango', nameLocal: 'மாம்பழம்', category: 'fruits', cuisine: 'global', servingSize: 100, commonServings: [{ label: '1 cup sliced (165g)', grams: 165 }, { label: '1 small mango (200g)', grams: 200 }], nutrients: { calories: 60, protein: 0.8, carbs: 15, netCarbs: 13.6, sugar: 13.7, fiber: 1.6, fat: 0.4, vitaminA: 1082, vitaminC: 36, vitaminB6: 0.12, vitaminB9: 43, vitaminK: 4.2, potassium: 168, sodium: 1 } },

  // VEGETABLES
  { name: 'Tomato', nameLocal: 'தக்காளி', category: 'vegetables', cuisine: 'global', servingSize: 100, commonServings: [{ label: '1 medium (123g)', grams: 123 }], nutrients: { calories: 18, protein: 0.9, carbs: 3.9, netCarbs: 2.7, sugar: 2.6, fiber: 1.2, fat: 0.2, vitaminA: 833, vitaminC: 13.7, vitaminK: 7.9, potassium: 237, sodium: 5 } },
  { name: 'Onion', nameLocal: 'வெங்காயம்', category: 'vegetables', cuisine: 'global', servingSize: 100, commonServings: [{ label: '1 medium (110g)', grams: 110 }], nutrients: { calories: 40, protein: 1.1, carbs: 9.3, netCarbs: 7.6, sugar: 4.2, fiber: 1.7, fat: 0.1, vitaminC: 7.4, vitaminB6: 0.12, vitaminB9: 19, potassium: 146, sodium: 4 } },
  { name: 'Carrot', nameLocal: 'கேரட்', category: 'vegetables', cuisine: 'global', servingSize: 100, commonServings: [{ label: '1 medium (61g)', grams: 61 }], nutrients: { calories: 41, protein: 0.9, carbs: 10, netCarbs: 7, sugar: 4.7, fiber: 2.8, fat: 0.2, vitaminA: 16706, vitaminB6: 0.14, vitaminC: 5.9, vitaminK: 13.2, calcium: 33, potassium: 320, sodium: 69 } },
  { name: 'Cucumber', nameLocal: 'வெள்ளரி', category: 'vegetables', cuisine: 'global', servingSize: 100, commonServings: [{ label: '1 cup sliced (119g)', grams: 119 }], nutrients: { calories: 16, protein: 0.7, carbs: 3.6, netCarbs: 3, sugar: 1.7, fiber: 0.5, fat: 0.1, vitaminC: 2.8, vitaminK: 16.4, potassium: 147, sodium: 2, water: 95 } },
  { name: 'Green Beans', nameLocal: 'பீன்ஸ்', category: 'vegetables', cuisine: 'global', servingSize: 100, commonServings: [{ label: '1 cup (100g)', grams: 100 }], nutrients: { calories: 31, protein: 1.8, carbs: 7, netCarbs: 4, sugar: 3.3, fiber: 2.7, fat: 0.2, vitaminA: 690, vitaminC: 12, vitaminK: 43, calcium: 37, iron: 1, potassium: 211, sodium: 6 } },
  { name: 'Cabbage', nameLocal: 'முட்டைக்கோஸ்', category: 'vegetables', cuisine: 'global', servingSize: 100, commonServings: [{ label: '1 cup shredded (89g)', grams: 89 }], nutrients: { calories: 25, protein: 1.3, carbs: 6, netCarbs: 4.2, sugar: 3.2, fiber: 2.5, fat: 0.1, vitaminC: 36, vitaminK: 76, vitaminB6: 0.12, calcium: 40, potassium: 170, sodium: 18 } },
  { name: 'Cauliflower', nameLocal: 'காலிஃபிளவர்', category: 'vegetables', cuisine: 'global', servingSize: 100, commonServings: [{ label: '1 cup (100g)', grams: 100 }], nutrients: { calories: 25, protein: 1.9, carbs: 5, netCarbs: 3, sugar: 1.9, fiber: 2, fat: 0.3, vitaminC: 48, vitaminB6: 0.18, vitaminK: 15.5, calcium: 22, potassium: 299, sodium: 30 } },
  { name: 'Spinach', nameLocal: 'கீரை', category: 'vegetables', cuisine: 'global', servingSize: 100, commonServings: [{ label: '1 cup (30g)', grams: 30 }], nutrients: { calories: 23, protein: 2.9, carbs: 3.6, netCarbs: 2, sugar: 0.4, fiber: 2.2, fat: 0.4, vitaminA: 9377, vitaminB9: 194, vitaminC: 28, vitaminK: 483, calcium: 99, iron: 2.7, magnesium: 79, potassium: 558, sodium: 79 } },
  { name: 'Broccoli', nameLocal: 'ப்ரோக்கோலி', category: 'vegetables', cuisine: 'global', servingSize: 100, commonServings: [{ label: '1 cup (91g)', grams: 91 }], nutrients: { calories: 34, protein: 2.8, carbs: 6.6, netCarbs: 4.1, sugar: 1.7, fiber: 2.6, fat: 0.4, vitaminA: 623, vitaminC: 89, vitaminK: 101, vitaminB9: 63, calcium: 47, iron: 0.7, potassium: 316, sodium: 33 } },
  { name: 'Potato', nameLocal: 'உருளைக்கிழங்கு', category: 'vegetables', cuisine: 'global', servingSize: 100, commonServings: [{ label: '1 medium boiled (150g)', grams: 150 }], nutrients: { calories: 77, protein: 2.0, carbs: 17, netCarbs: 15.4, sugar: 0.8, fiber: 2.2, fat: 0.1, vitaminC: 19.7, vitaminB6: 0.3, vitaminB3: 1.1, iron: 0.8, potassium: 421, sodium: 6 } },
  { name: 'Sweet Potato', nameLocal: 'சேனைக்கிழங்கு', category: 'vegetables', cuisine: 'global', servingSize: 100, commonServings: [{ label: '1 medium (130g)', grams: 130 }], nutrients: { calories: 86, protein: 1.6, carbs: 20, netCarbs: 17, sugar: 4.2, fiber: 3, fat: 0.1, vitaminA: 14187, vitaminB6: 0.3, vitaminC: 2.4, vitaminB9: 11, calcium: 30, iron: 0.6, potassium: 337, sodium: 55 } },

  // SNACKS
  { name: 'Murukku', nameLocal: 'முறுக்கு', category: 'snacks', cuisine: 'south_indian', servingSize: 100, commonServings: [{ label: '2 pieces (30g)', grams: 30 }], nutrients: { calories: 435, protein: 8, carbs: 64, netCarbs: 62, sugar: 1, fiber: 2, fat: 17, saturatedFat: 3, sodium: 520 } },
  { name: 'Sundal', nameLocal: 'சுண்டல்', category: 'snacks', cuisine: 'south_indian', servingSize: 100, commonServings: [{ label: '1 cup (100g)', grams: 100 }], nutrients: { calories: 130, protein: 8, incompleteProtein: 8, carbs: 20, netCarbs: 14, sugar: 2, fiber: 6, fat: 3, saturatedFat: 1.5, calcium: 50, iron: 2, potassium: 290, sodium: 200 } },
  { name: 'Peanut Chikki', nameLocal: 'வேர்க்கடலை சிக்கி', category: 'snacks', cuisine: 'south_indian', servingSize: 100, commonServings: [{ label: '1 piece (25g)', grams: 25 }], nutrients: { calories: 450, protein: 12, carbs: 60, netCarbs: 57, sugar: 40, fiber: 3, fat: 20, saturatedFat: 3, iron: 2, potassium: 350, sodium: 50 } },
  { name: 'Roasted Peanuts', nameLocal: 'வறுத்த வேர்க்கடலை', category: 'snacks', cuisine: 'global', servingSize: 100, commonServings: [{ label: 'Handful (30g)', grams: 30 }], nutrients: { calories: 585, protein: 24, incompleteProtein: 24, carbs: 21, netCarbs: 15, sugar: 4, fiber: 6, fat: 50, saturatedFat: 7, monounsaturatedFat: 24, omega6: 15, vitaminB3: 13, vitaminE: 8, iron: 2.3, magnesium: 176, sodium: 370, zinc: 3.3 } },
  { name: 'Boiled Peanuts', nameLocal: 'வேர்க்கடலை (வேகவைத்த)', category: 'snacks', cuisine: 'south_indian', servingSize: 100, commonServings: [{ label: '1 cup (150g)', grams: 150 }], nutrients: { calories: 318, protein: 13.5, incompleteProtein: 13.5, carbs: 22, netCarbs: 17, sugar: 4, fiber: 5, fat: 22, saturatedFat: 3, omega6: 8, vitaminB9: 145, iron: 1.8, magnesium: 63, potassium: 390, sodium: 220 } },

  // DRINKS
  { name: 'Tea', nameLocal: 'தேநீர்', category: 'drinks', cuisine: 'indian', servingSize: 100, commonServings: [{ label: '1 cup (200ml)', grams: 200 }], nutrients: { calories: 30, protein: 0.9, carbs: 3.5, netCarbs: 3.5, sugar: 3.5, fiber: 0, fat: 1.2, saturatedFat: 0.8, calcium: 35, sodium: 15, potassium: 70 } },
  { name: 'Coffee', nameLocal: 'காபி', category: 'drinks', cuisine: 'south_indian', servingSize: 100, commonServings: [{ label: '1 cup (200ml)', grams: 200 }], nutrients: { calories: 35, protein: 1.0, carbs: 4, netCarbs: 4, sugar: 3.5, fiber: 0, fat: 1.5, saturatedFat: 1.0, calcium: 38, sodium: 20, potassium: 80 } },
  { name: 'Tender Coconut Water', nameLocal: 'இளநீர்', category: 'drinks', cuisine: 'south_indian', servingSize: 100, commonServings: [{ label: '1 coconut (300ml)', grams: 300 }], nutrients: { calories: 19, protein: 0.7, carbs: 3.7, netCarbs: 3.5, sugar: 2.6, fiber: 1.1, fat: 0.2, vitaminC: 2.4, calcium: 24, iron: 0.3, magnesium: 25, phosphorus: 20, potassium: 250, sodium: 105 } },
  { name: 'Lassi', nameLocal: 'லஸ்ஸி', category: 'drinks', cuisine: 'indian', servingSize: 100, commonServings: [{ label: '1 glass (250ml)', grams: 250 }], nutrients: { calories: 65, protein: 3.2, carbs: 8, netCarbs: 8, sugar: 7, fiber: 0, fat: 2.5, saturatedFat: 1.5, calcium: 110, sodium: 60, potassium: 150 } },

  // BIRYANI
  { name: 'Chicken Biryani', nameLocal: 'சிக்கன் பிரியாணி', category: 'lunch', cuisine: 'south_indian', servingSize: 100, tags: ['biryani', 'rice', 'chicken', 'briyani'], commonServings: [{ label: '1 plate (350g)', grams: 350 }, { label: '1 cup (200g)', grams: 200 }, { label: 'Half plate (175g)', grams: 175 }], nutrients: { calories: 168, protein: 9.5, carbs: 18, netCarbs: 17, sugar: 1.5, fiber: 1, fat: 6.5, saturatedFat: 2, cholesterol: 45, vitaminB3: 4, calcium: 25, iron: 1.2, potassium: 220, sodium: 480 } },
  { name: 'Mutton Biryani', nameLocal: 'ஆட்டு பிரியாணி', category: 'lunch', cuisine: 'south_indian', servingSize: 100, tags: ['biryani', 'rice', 'mutton', 'briyani', 'lamb'], commonServings: [{ label: '1 plate (350g)', grams: 350 }, { label: '1 cup (200g)', grams: 200 }, { label: 'Half plate (175g)', grams: 175 }], nutrients: { calories: 185, protein: 11, carbs: 17, netCarbs: 16, sugar: 1.2, fiber: 1, fat: 8, saturatedFat: 3, cholesterol: 55, iron: 2, zinc: 2.5, potassium: 240, sodium: 510 } },
  { name: 'Veg Biryani', nameLocal: 'வெஜ் பிரியாணி', category: 'lunch', cuisine: 'south_indian', servingSize: 100, tags: ['biryani', 'rice', 'vegetarian', 'briyani'], commonServings: [{ label: '1 plate (300g)', grams: 300 }, { label: '1 cup (200g)', grams: 200 }], nutrients: { calories: 148, protein: 3.5, carbs: 22, netCarbs: 20.5, sugar: 2, fiber: 1.5, fat: 5.5, saturatedFat: 1.5, vitaminA: 200, vitaminC: 5, calcium: 30, iron: 0.8, potassium: 180, sodium: 420 } },
  { name: 'Egg Biryani', nameLocal: 'முட்டை பிரியாணி', category: 'lunch', cuisine: 'south_indian', servingSize: 100, tags: ['biryani', 'rice', 'egg', 'briyani'], commonServings: [{ label: '1 plate (300g)', grams: 300 }], nutrients: { calories: 162, protein: 8, carbs: 18, netCarbs: 17, sugar: 1, fiber: 1, fat: 7, saturatedFat: 2, cholesterol: 120, calcium: 40, iron: 1.5, potassium: 200, sodium: 450 } },

  // MORE SOUTH INDIAN BREAKFAST
  { name: 'Pesarattu (Green Gram Dosa)', nameLocal: 'பெசரட்டு', category: 'breakfast', cuisine: 'south_indian', servingSize: 100, tags: ['dosa', 'green gram', 'moong', 'breakfast', 'healthy'], commonServings: [{ label: '1 piece (120g)', grams: 120 }], nutrients: { calories: 150, protein: 6, carbs: 22, netCarbs: 20, sugar: 1, fiber: 2, fat: 4, saturatedFat: 0.8, iron: 1.5, sodium: 180 } },
  { name: 'Adai', nameLocal: 'அடை தோசை', category: 'breakfast', cuisine: 'south_indian', servingSize: 100, tags: ['dosa', 'lentil', 'protein', 'breakfast'], commonServings: [{ label: '1 piece (150g)', grams: 150 }], nutrients: { calories: 180, protein: 7, carbs: 26, netCarbs: 23, sugar: 1, fiber: 3, fat: 5, saturatedFat: 1, iron: 2.1, sodium: 220 } },
  { name: 'Kuzhi Paniyaram (Sweet)', nameLocal: 'இனிப்பு குழி பணியாரம்', category: 'breakfast', cuisine: 'south_indian', servingSize: 100, tags: ['sweet', 'paniyaram', 'jaggery'], commonServings: [{ label: '5 pieces (100g)', grams: 100 }], nutrients: { calories: 230, protein: 3, carbs: 42, netCarbs: 41, sugar: 20, fiber: 1, fat: 6, saturatedFat: 2, calcium: 15, sodium: 50 } },
  { name: 'Upma (Rice)', nameLocal: 'அரிசி உப்மா', category: 'breakfast', cuisine: 'south_indian', servingSize: 100, tags: ['upma', 'rice'], commonServings: [{ label: '1 cup (200g)', grams: 200 }], nutrients: { calories: 110, protein: 2, carbs: 20, netCarbs: 19, sugar: 0.5, fiber: 1, fat: 2, saturatedFat: 1, sodium: 220 } },
  { name: 'Puttu', nameLocal: 'புட்டு', category: 'breakfast', cuisine: 'south_indian', servingSize: 100, tags: ['kerala', 'rice', 'coconut'], commonServings: [{ label: '1 piece (100g)', grams: 100 }], nutrients: { calories: 165, protein: 3, carbs: 32, netCarbs: 30, sugar: 2, fiber: 2, fat: 3.5, saturatedFat: 2.5, sodium: 80 } },
  { name: 'Kadala Curry', nameLocal: 'கடலை கறி', category: 'breakfast', cuisine: 'south_indian', servingSize: 100, tags: ['kerala', 'chickpeas', 'curry'], commonServings: [{ label: '1 serving (150g)', grams: 150 }], nutrients: { calories: 140, protein: 6, carbs: 16, netCarbs: 12, sugar: 2, fiber: 4, fat: 6, saturatedFat: 4, iron: 2, sodium: 260 } },
  
  // MORE SOUTH INDIAN SNACKS
  { name: 'Medu Vada', nameLocal: 'மெது வடை', category: 'snacks', cuisine: 'south_indian', servingSize: 100, tags: ['vada', 'vadai', 'snack', 'fried'], commonServings: [{ label: '1 piece (45g)', grams: 45 }, { label: '2 pieces (90g)', grams: 90 }], nutrients: { calories: 290, protein: 9, carbs: 32, netCarbs: 29, sugar: 0, fiber: 3, fat: 14, saturatedFat: 3, iron: 2, sodium: 350 } },
  { name: 'Masala Vada', nameLocal: 'மசால் வடை', category: 'snacks', cuisine: 'south_indian', servingSize: 100, tags: ['vada', 'vadai', 'paruppu vada'], commonServings: [{ label: '1 piece (40g)', grams: 40 }], nutrients: { calories: 280, protein: 12, carbs: 28, netCarbs: 24, sugar: 1, fiber: 4, fat: 12, saturatedFat: 2, iron: 2.5, sodium: 320 } },
  { name: 'Bajji (Plantain)', nameLocal: 'வாழைக்காய் பஜ்ஜி', category: 'snacks', cuisine: 'south_indian', servingSize: 100, tags: ['bajji', 'fried', 'banana'], commonServings: [{ label: '1 piece (50g)', grams: 50 }], nutrients: { calories: 260, protein: 3, carbs: 32, netCarbs: 29, sugar: 2, fiber: 3, fat: 12, saturatedFat: 2, sodium: 280 } },
  { name: 'Mysore Pak', nameLocal: 'மைசூர் பாக்', category: 'snacks', cuisine: 'south_indian', servingSize: 100, tags: ['sweet', 'ghee'], commonServings: [{ label: '1 piece (40g)', grams: 40 }], nutrients: { calories: 480, protein: 5, carbs: 45, netCarbs: 45, sugar: 40, fiber: 0, fat: 30, saturatedFat: 18, sodium: 5 } },
  { name: 'Payasam', nameLocal: 'பாயாசம்', category: 'snacks', cuisine: 'south_indian', servingSize: 100, tags: ['sweet', 'kheer'], commonServings: [{ label: '1 cup (150ml)', grams: 150 }], nutrients: { calories: 155, protein: 2, carbs: 28, netCarbs: 27, sugar: 22, fiber: 1, fat: 5, saturatedFat: 3, calcium: 60, sodium: 40 } },
  { name: 'Kozhukattai (Sweet)', nameLocal: 'இனிப்பு கொழுக்கட்டை', category: 'snacks', cuisine: 'south_indian', servingSize: 100, tags: ['modak', 'sweet', 'steamed'], commonServings: [{ label: '1 piece (50g)', grams: 50 }], nutrients: { calories: 180, protein: 2, carbs: 36, netCarbs: 34, sugar: 15, fiber: 2, fat: 4, saturatedFat: 3, sodium: 10 } },
  { name: 'Mixture (South Indian)', nameLocal: 'மிக்சர்', category: 'snacks', cuisine: 'south_indian', servingSize: 100, tags: ['mixture', 'savory', 'fried'], commonServings: [{ label: '1 small cup (50g)', grams: 50 }], nutrients: { calories: 450, protein: 10, carbs: 45, netCarbs: 41, sugar: 2, fiber: 4, fat: 28, saturatedFat: 6, sodium: 450 } },

  // MORE CURRIES & CHUTNEYS
  { name: 'Coconut Chutney', nameLocal: 'தேங்காய் சட்னி', category: 'lunch', cuisine: 'south_indian', servingSize: 100, tags: ['chutney', 'sides'], commonServings: [{ label: '2 tbsp (30g)', grams: 30 }, { label: '1/4 cup (60g)', grams: 60 }], nutrients: { calories: 160, protein: 2, carbs: 5, netCarbs: 3, sugar: 2, fiber: 2, fat: 15, saturatedFat: 13, sodium: 280 } },
  { name: 'Tomato Chutney', nameLocal: 'தக்காளி சட்னி', category: 'lunch', cuisine: 'south_indian', servingSize: 100, tags: ['chutney', 'sides'], commonServings: [{ label: '2 tbsp (30g)', grams: 30 }, { label: '1/4 cup (60g)', grams: 60 }], nutrients: { calories: 85, protein: 2, carbs: 6, netCarbs: 4, sugar: 3, fiber: 2, fat: 6, saturatedFat: 1, sodium: 320 } },
  { name: 'Mint Chutney (Pudina)', nameLocal: 'புதினா சட்னி', category: 'lunch', cuisine: 'south_indian', servingSize: 100, tags: ['chutney', 'sides', 'pudina'], commonServings: [{ label: '2 tbsp (30g)', grams: 30 }], nutrients: { calories: 60, protein: 2, carbs: 6, netCarbs: 4, sugar: 2, fiber: 2, fat: 3, saturatedFat: 0.5, sodium: 250 } },
  { name: 'Poondu Kuzhambu (Garlic Curry)', nameLocal: 'பூண்டு குழம்பு', category: 'lunch', cuisine: 'south_indian', servingSize: 100, tags: ['curry', 'garlic'], commonServings: [{ label: '1 ladle (100ml)', grams: 100 }], nutrients: { calories: 120, protein: 3, carbs: 12, netCarbs: 10, sugar: 3, fiber: 2, fat: 7, saturatedFat: 1, sodium: 380 } },
  { name: 'Vatha Kuzhambu', nameLocal: 'வற்றல் குழம்பு', category: 'lunch', cuisine: 'south_indian', servingSize: 100, tags: ['curry', 'tangy'], commonServings: [{ label: '1 ladle (100ml)', grams: 100 }], nutrients: { calories: 110, protein: 2.5, carbs: 14, netCarbs: 12, sugar: 4, fiber: 2, fat: 6, saturatedFat: 1, sodium: 450 } },
  { name: 'Keerai Masiyal', nameLocal: 'கீரை மசியல்', category: 'lunch', cuisine: 'south_indian', servingSize: 100, tags: ['spinach', 'mash', 'curry'], commonServings: [{ label: '1 cup (150g)', grams: 150 }], nutrients: { calories: 75, protein: 4, carbs: 10, netCarbs: 6, sugar: 1, fiber: 4, fat: 3, saturatedFat: 0.5, iron: 3.5, sodium: 250 } },
  { name: 'Meen Varuval (Fish Fry)', nameLocal: 'மீன் வறுவல்', category: 'lunch', cuisine: 'south_indian', servingSize: 100, tags: ['fish', 'fry', 'seafood'], commonServings: [{ label: '1 piece (100g)', grams: 100 }], nutrients: { calories: 230, protein: 20, carbs: 5, netCarbs: 4, sugar: 0, fiber: 1, fat: 14, saturatedFat: 3, iron: 1.5, sodium: 400 } },
  { name: 'Chicken 65', nameLocal: 'சிக்கன் 65', category: 'snacks', cuisine: 'south_indian', servingSize: 100, tags: ['chicken', 'fry', 'starter'], commonServings: [{ label: '1 serving (150g)', grams: 150 }], nutrients: { calories: 280, protein: 18, carbs: 12, netCarbs: 11, sugar: 1, fiber: 1, fat: 18, saturatedFat: 4, sodium: 600 } },

  // OATS & HEALTHY CEREALS
  { name: 'Yogabar High Protein Oats', nameLocal: 'யோகாபார் புரோட்டீன் ஓட்ஸ்', category: 'breakfast', cuisine: 'global', servingSize: 100, tags: ['oats', 'protein', 'yogabar', 'high protein', 'cereal', 'healthy'], commonServings: [{ label: '1 sachet (55g)', grams: 55 }, { label: '1 cup (100g)', grams: 100 }], nutrients: { calories: 380, protein: 20, carbs: 52, netCarbs: 47, sugar: 6, fiber: 5, fat: 7, saturatedFat: 1.5, calcium: 120, iron: 5, sodium: 280, potassium: 350 } },
  { name: 'Oats (Rolled)', nameLocal: 'ஓட்ஸ்', category: 'breakfast', cuisine: 'global', servingSize: 100, tags: ['oats', 'oatmeal', 'cereal', 'quaker', 'porridge'], commonServings: [{ label: '1 cup dry (80g)', grams: 80 }, { label: '1 cup cooked (240g)', grams: 240 }, { label: '40g serving', grams: 40 }], nutrients: { calories: 389, protein: 16.9, carbs: 66, netCarbs: 57.6, sugar: 1, fiber: 10.6, fat: 6.9, saturatedFat: 1.2, polyunsaturatedFat: 2.5, vitaminB1: 0.76, vitaminB5: 1.3, calcium: 54, iron: 4.7, magnesium: 138, phosphorus: 410, potassium: 429, sodium: 2, zinc: 4, selenium: 34 } },
  { name: 'Quaker Oats', nameLocal: 'குவேக்கர் ஓட்ஸ்', category: 'breakfast', cuisine: 'global', servingSize: 100, tags: ['oats', 'cereal', 'quaker', 'porridge'], commonServings: [{ label: '30g serving', grams: 30 }, { label: '40g serving', grams: 40 }], nutrients: { calories: 375, protein: 13, carbs: 67, netCarbs: 57, sugar: 1, fiber: 10, fat: 7, saturatedFat: 1.3, calcium: 52, iron: 3.8, sodium: 5 } },
  { name: 'Muesli', nameLocal: 'முயெஸ்லி', category: 'breakfast', cuisine: 'global', servingSize: 100, tags: ['muesli', 'oats', 'cereal', 'granola', 'healthy'], commonServings: [{ label: '45g serving', grams: 45 }, { label: '60g serving', grams: 60 }], nutrients: { calories: 366, protein: 9.8, carbs: 67, netCarbs: 59, sugar: 18, fiber: 8, fat: 7, saturatedFat: 1.2, calcium: 82, iron: 4, potassium: 400, sodium: 160 } },


  // MORE PROTEINS
  { name: 'Whey Protein Shake', nameLocal: 'வே புரோட்டீன்', category: 'protein', cuisine: 'global', servingSize: 100, tags: ['protein', 'whey', 'shake', 'supplement', 'gym'], commonServings: [{ label: '1 scoop (30g)', grams: 30 }, { label: '2 scoops (60g)', grams: 60 }], nutrients: { calories: 370, protein: 75, carbs: 7, netCarbs: 5, sugar: 3, fiber: 2, fat: 5, saturatedFat: 2, calcium: 300, sodium: 200, potassium: 500 } },
];


const seed = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('✅ Connected to MongoDB');

    await Food.deleteMany({});
    console.log('🗑️  Cleared existing foods');

    const inserted = await Food.insertMany(foods);
    console.log(`✅ Inserted ${inserted.length} foods`);

    // Verify
    const count = await Food.countDocuments();
    console.log(`📊 Total foods in DB: ${count}`);

    await mongoose.disconnect();
    console.log('✅ Seed completed successfully!');
    process.exit(0);
  } catch (error) {
    console.error('❌ Seed error:', error);
    process.exit(1);
  }
};

seed();
